# Generated by Django 4.2.26 on 2025-12-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='official_instagram',
            field=models.URLField(blank=True, help_text='公式Instagram'),
        ),
        migrations.AddField(
            model_name='work',
            name='official_site',
            field=models.URLField(blank=True, help_text='公式サイト'),
        ),
        migrations.AddField(
            model_name='work',
            name='official_tiktok',
            field=models.URLField(blank=True, help_text='公式TikTok'),
        ),
        migrations.AddField(
            model_name='work',
            name='official_x',
            field=models.URLField(blank=True, help_text='公式X（Twitter）'),
        ),
    ]
