# Generated by Django 4.2.26 on 2025-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_work_official_instagram_work_official_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # TaggableManager を削除
        migrations.RemoveField(
            model_name='viewinglog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='work',
            name='tags',
        ),
        # ManyToManyField で再作成
        migrations.AddField(
            model_name='viewinglog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='ログ用タグ（泣いた、初見、千秋楽など）', related_name='logs', to='api.tag'),
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='作品タグ（会話劇、一人芝居、SF など）', related_name='works', to='api.tag'),
        ),
    ]
