# Generated by Django 4.2.26 on 2025-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_alter_viewinglog_tags_alter_work_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinglog',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='1.0〜5.0の評価（小数点第一位まで）', max_digits=3, null=True),
        ),
    ]
