# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_viewinglog_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_quick_created',
            field=models.BooleanField(default=False),
        ),
    ]
