# Generated by Django 4.2.29 on 2026-03-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '一般ユーザー'), ('shop', '店舗ユーザー'), ('admin', '管理者')], default='user', max_length=20),
        ),
    ]
