# Generated by Django 4.2.29 on 2026-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
