# Generated by Django 4.2.29 on 2026-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_add_shop_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='shops/'),
        ),
    ]
