# Generated by Django 4.2.29 on 2026-03-12 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewinglog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='viewinglog',
            name='status',
            field=models.CharField(choices=[('watched', '観た'), ('planned', 'これから観る')], default='watched', max_length=20),
        ),
        migrations.AlterField(
            model_name='viewinglog',
            name='watched_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'review')},
            },
        ),
    ]
