# Generated by Django 4.2.29 on 2026-03-16 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_viewinglog_options_viewinglog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinglog',
            name='watched_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_overall',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '観た'), (4, '良かった'), (5, '最高')], null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
