# Generated by Django 4.2.29 on 2026-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_watched_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viewinglog',
            constraint=models.UniqueConstraint(fields=('user', 'performance'), name='unique_user_performance'),
        ),
    ]
