# Generated by Django 4.2.29 on 2026-03-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_unique_user_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_public_id', models.CharField(blank=True, default='', max_length=300)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewing_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.viewinglog')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
