# Generated by Django 4.2.29 on 2026-03-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
